### ISSUE TITLE
visualize a fort.63

### ISSUE THREAD

**Issue by krober10nd** [oceanmodeling/adcircpy#102]
* How does one create an animation (.gif, etc.) of a fort.63?

**Comment by jreniel** [comment]
Using FuncAnim from matplotlib, but the fastest most efficient way is dumping the frames to png then use imageio to generate the gif. Sorry I don't have this code implemented in adcircpy. I can share the code with you more likely tomorrow than today. I don't have that pushed to any public repos yet.

**Comment by krober10nd** [comment]
thanks Jaime. I was perusing the outputs/fort63.py code and saw some functions to create animations but they weren't hooked up to the the cmdline interface. 

The use case I had in mind would be to automatically make a quick gif of the free surface animation in an area of interest (could be a subdomain) to verify the simulations are working correctly. This would be in addition to a maxele plot.

**Comment by krober10nd** [comment]
hey @jreniel if you provide any more information on this, it would be much appreciated.

**Comment by jreniel** [comment]
@krober10nd
Sure. What exactly do we need to build? A CLI interface for generating movies?

**Comment by krober10nd** [comment]
That's what I'm thinking about. Something to produce visualizations of the water surface elevation as a function of time.

**Comment by jreniel** [comment]
> That's what I'm thinking about. Something to produce visualizations of the water surface elevation as a function of time.

Do you mind meeting with me for 15-30 minutes? I'm not sure on which email to contact you, but let me know your availability (the sooner the better, it can be today even) over my noaa.gov email. Thanks!

**Comment by krober10nd** [comment]
Sure, `keithrbt0@gmail.com` is my personal one. That works. I can meet in about an hour at 2 pm EST if you'd like.

**Comment by krober10nd** [comment]
This ended up being really simple 

```
 from adcircpy.outputs import Fort63
 
 
 fname = "exp011b.63.nc"
 fort63 = Fort63(fname)
 anim = fort63.animation(save='testing.gif', end_frame=20, xmin=-75, xmax=-73, ymin=40.00, ymax=41.5)

```
