### ISSUE TITLE
how to control numerical parameters chosen for fort15 creation?

### ISSUE THREAD

**Issue by krober10nd** [oceanmodeling/adcircpy#113]
* There seems to be a significant amount of assumptions regarding the numerical parameters chosen for a simulation (e.g., timestep, IM-type, horizontal dissipation, non-fatal override, etc.). 
* How does one tune these options to their particular case at the scripting level?

**Comment by jreniel** [comment]
Would doing something like [this](https://github.com/jreniel/adcircpy/blob/main/examples/example_1.py#L43-L50) work for you?

**Comment by krober10nd** [comment]
Yep, that works. Great.

**Comment by jreniel** [comment]
Good to hear!
