### ISSUE TITLE
NFOVER treatment

### ISSUE THREAD

**Issue by krober10nd** [oceanmodeling/adcircpy#114]
* In the case the user has compiled ADCIRC with DEBUG_ELEVATION compiler flag, the parameter NFOVER becomes a vector of 4 values. 
* Can we handle this case inside fort.15? Currently, it causes a segfault
* For example
```
driver.NFOVER = [1 ,6, 0, 50, 8]
```

**Comment by jreniel** [comment]
You will have to modify the [@NFOVER.setter](https://github.com/jreniel/adcircpy/blob/main/adcircpy/fort15.py#L1951-L1954) and make sure the [fort.15 writer](https://github.com/jreniel/adcircpy/blob/0bec96bf16c7f5e4899c62a8cfaa555e16842d8b/adcircpy/fort15.py#L35) can handle it.
