### ISSUE TITLE
no convex hull

### ISSUE THREAD

**Issue by jreniel** [oceanmodeling/adcircpy#122]
I can guarantee you that a convex hull is not what represents the mesh's outer boundary. This breaks a lot of things.
https://github.com/jreniel/adcircpy/blob/5618de27360bced8d796168b6e70c1c0c0959b7c/adcircpy/mesh/base.py#L310

There's no reason for the "hull" of a mesh to be convex. In fact in most cases it is concave! Making a convex assumption is simply mathematically incorrect.
This is similar to the conversation we were having a few year ago about _not_ using alpha shapes. Alpha shapes and the convex hull are not appropriate to compute the mesh's outer shell.

**Comment by jreniel** [comment]
![image](https://user-images.githubusercontent.com/19892302/131218984-21af497b-10d0-4a28-8503-47cf9386377e.png)
In purple, there's a quarter moon to simulate your mesh's boundary. In red is the convex hull object of the quarter moon. The convex hull _does not_ represent the outer boundary of a mesh.

**Comment by jreniel** [comment]
For API breaking changes you are free to create your own fork, or please discuss first your idea.

**Comment by ghost** [comment]
i added the convex hull to the steps as a fallback, in case the larger exterior hull of the mesh was not found. The algorithm found the exterior hull for the shinnecock mesh, but for some reason failed to find it for the 250m subsetted Florence mesh that William provided, so I wanted to add this step so that some approximation of a hull at least makes it into the final polygon

**Comment by jreniel** [comment]
Then there is something wrong with your algorithm. The mesh boundary is well defined and can always be found.

**Comment by jreniel** [comment]
Does the algorithm that's currently implemented fails? Don't fix it if it ain't broken. Or at least make sure to fix it right.

**Comment by ghost** [comment]
> Does the algorithm that's currently implemented fails? Don't fix it if it ain't broken. Or at least make sure to fix it right.

I was running into memory issues when running multiple perturbations on Hera on the 120m mesh, but that may be a problem with the mesh topology. I'll test it on the different meshes that we have

**Comment by krober10nd** [comment]
I couldn't read the whole thread, I apologize. However, if you need the boundary of a triangular mesh, I wrote an algorithm that walks the edges of the mesh in an ordered fashion (i.e. ccw or cw). It's quick. Then you convert that boundary to a shapely polygon or something and do your tasks with it. 

https://github.com/krober10nd/SeismicMesh/blob/38818938405b4b1126463944af949a3368f79b5c/SeismicMesh/geometry/utils.py#L329

**Comment by jreniel** [comment]
> I couldn't read the whole thread, I apologize. However, if you need the boundary of a triangular mesh, I wrote an algorithm that walks the edges of the mesh in an ordered fashion (i.e. ccw or cw). It's quick. Then you convert that boundary to a shapely polygon or something and do your tasks with it.
> 
> https://github.com/krober10nd/SeismicMesh/blob/38818938405b4b1126463944af949a3368f79b5c/SeismicMesh/geometry/utils.py#L329

I think this is already fixed, but the Fort14/AdcircMesh classes will give you both the exterior and interior edges. It will also work with degenerate meshes, such as the HSOFS, which have multiple exterior boundaries. To use it: 
```python
exteriors = mesh.rings.exterior()
interiors = mesh.rings.interior()
mp = mesh.hull.multipolygon()
```

**Comment by krober10nd** [comment]
so why do we need a convex hull?

**Comment by jreniel** [comment]
> so why do we need a convex hull?

We don't, and we shouldn't! The topological boundaries must be derived from the connectivity table. Using a convex hull will result in erroneous outputs. That was my whole point here, convex hulls and alpha shapes are "forbidden"!

But there was a bug in `mp = mesh.hull.multipolygon()` which is what I think prompted this. However, @zacharyburnettNOAA  says he's running out of memory... (?) That hasn't happened to me though, so I don't know...

**Comment by krober10nd** [comment]
Gotcha I agree. Next time I'll read. ;)

**Comment by jreniel** [comment]
> Gotcha I agree. Next time I'll read. ;)

No worries, this was a long convo actually, which connects to another PR.
