### ISSUE TITLE
incorrect besttrack start time in `WTIMINC` but only for `nws=8`

### ISSUE THREAD

**Issue by ghost** [oceanmodeling/adcircpy#123]
when running from `besttrack`on `nws=8`, ADCIRC gives the following error:
```
ERROR: getHollandStormData: The fort.22 file ends before RNDAY.
ERROR: windTerminate: ADCIRC terminating.
```
I've checked that the modeled forcing start time (at the bottom of `fort.15`) is consistent with the beginning of the `fort.22`, but @WPringle tells me that it should actually be consistent with the beginning of *spinup* time, and that is why it is breaking (it's starting late and ending past the end of the `fort.22`)

related issue:
https://github.com/noaa-ocs-modeling/EnsemblePerturbation/issues/40#issuecomment-902145979

I'm working on a fix that uses the spinup start time instead of the run start.

**Comment by krober10nd** [comment]
in my experience this *can be* related to #116. Sometimes the formatting of a decimal `RNDAY` is incrementally too short compared to what ADCIRC calculates (2 decimal places).

**Comment by krober10nd** [comment]
```
@WPringle tells me that it should actually be consistent with the beginning of spinup time, and that is why it is breaking (it's starting late and ending past the end of the fort.22)
```

The RNDAY should be the length of the *entire* run. In practical configurations what you do is a tide-only run up to the start day of the wind run, then launch a hot start with potentially a short meteorological ramp (DRAMP in ADCIRC) with the tides at full bore. 

The other option with the hot start/cold start combo could be inserting blank snaps in the fort.22 file so the start times correctly correspond. It's easy to manually modify the NWS=8 track file if that's what you want.

**Comment by ghost** [comment]
@WPringle was able to run a run successfully with `nws=8` by changing the `WTIMINC` to reference the **coldstart** start time instead of the start time of the hotstart. I will look into implementation of this for `nws=8`

**Comment by saeed-moghimi-noaa** [comment]
Resolved
