### ISSUE TITLE
best_track_file error

### ISSUE THREAD

**Issue by krober10nd** [oceanmodeling/adcircpy#37]
* After installing `adcircpy` via `pip install adcircpy` I wanted to use the best_track_file functionality to produce a fort.20 from a best track (Hurricane Sandy). 
* Unfortunately it seems that some modules were moved around creating a segfault. 
* MWE 
```
(base) keiths-MacBook-Pro:KeithJaredR Keith$ best_track_file -h
Traceback (most recent call last):
  File "/Applications/miniconda3/bin/best_track_file", line 5, in <module>
    from adcircpy.cmd.best_track_file import main
  File "/Applications/miniconda3/lib/python3.7/site-packages/adcircpy/cmd/best_track_file.py", line 4, in <module>
    from adcircpy.forcing.winds.best_track import BestTrackForcing
  File "/Applications/miniconda3/lib/python3.7/site-packages/adcircpy/forcing/winds/best_track.py", line 10, in <module>
    from adcircpy.forcing.winds.base import _WindForcing
ModuleNotFoundError: No module named 'adcircpy.forcing.winds.base'
```

**Comment by ghost** [comment]
@zacharyburnettNOAA I've updated pip to v1.0.13 but dunamai doesn't seem to be pip friendly. Can you test and suggest a fix? Thanks!

**Comment by krober10nd** [comment]
thanks @JaimeCalzadaNOAA I was able to get around it by just typing `best_track_file`, however, some of the kwarg args didn't appear to do anything (like remove entries with "EX" or "TS" or write to a specified text file). 

It's no big deal but just a heads up.

**Comment by jreniel** [comment]
> thanks @JaimeCalzadaNOAA I was able to get around it by just typing `best_track_file`, however, some of the kwarg args didn't appear to do anything (like remove entries with "EX" or "TS" or write to a specified text file).
> 
> It's no big deal but just a heads up.

Hi @krober10nd,  thanks for trying out the package. Removing EX or TS was once enabled, but there's an ambiguity to it that I was never able to fully resolve. In particular, there are storms which can have some EX records, then back to HU, then back to EX, and the same thing happens with TS. So what do we do? Do we cut it at the first EX or do we just filter out those entries? My advice is that you run the entire output. In fact, I would recommend that you use the `best_track_run` entrypoint instead.

Additionally, I encourage you to submit your contributions via a pull-request. A lot of what we need to run ADCIRC is already part of ADCIRCPy, but it needs more users willing to submit bug-reports and fixes.

Thanks for your time!

**Comment by krober10nd** [comment]
> Hi @krober10nd, thanks for trying out the package. Removing EX or TS was once enabled, but there's an ambiguity to it that I was never able to fully resolve. In particular, there are storms which can have some EX records, then back to HU, then back to EX, and the same thing happens with TS. So what do we do? Do we cut it at the first EX or do we just filter out those entries? My advice is that you run the entire output. In fact, I would recommend that you use the best_track_run entrypoint instead.

You're welcome. That makes sense. 

> Additionally, I encourage you to submit your contributions via a pull-request. A lot of what we need to run ADCIRC is already part of ADCIRCPy, but it needs more users willing to submit bug-reports and fixes.

One thing that could be useful to get your code more visibility is putting it on the [adcirc wiki](https://www.google.com/search?client=safari&rls=en&q=adcirc+wiki&ie=UTF-8&oe=UTF-8)

and or adding a note in the adcirc.org website to note the workflow to build the fort.22 file for use with the GAHM.

**Comment by jreniel** [comment]
Thanks Keith. I will mark this issue as resolved, but please feel free to open a new one if you find any other issues.
