### ISSUE TITLE
Dunamai Version.from_any_vcs() on setup.py is not compatible with pip deployments.

### ISSUE THREAD

**Issue by jreniel** [oceanmodeling/adcircpy#38]
@zacharyburnettNOAA I've updated pip to v1.0.13 but dunamai doesn't seem to be pip friendly. Can you test and suggest a fix? Thanks!

_Originally posted by @JaimeCalzadaNOAA in https://github.com/JaimeCalzadaNOAA/adcircpy/issues/37#issuecomment-765020363_

**Comment by jreniel** [comment]
`pip install adcircpy` fails with `RuntimeError: Unable to detect version control system.`

**Comment by ghost** [comment]
it looks like there's only the source `.tar.gz` here in the release files (https://pypi.org/project/adcircpy/1.0.13/#files) so pip is building the package from source:
```
adcircpy-1.0.13.tar.gz
```
Whenever I've used dunamai before it's been deployed as a wheel, so it never needed to build from anything that isn't already a git repository.

Is there supposed to be a compiled wheel as well? If not, I can add some contingencies for building from source outside of VCS

**Comment by jreniel** [comment]
If we wanted to build cross-platform deployments, we'd have to establish build pipelines. Can we make it work while keeping it simple? If not, then we probably should reconsider versioneer (although there is probably a way to make it happen with dunamai).

**Comment by ghost** [comment]
> If we wanted to build cross-platform deployments, we'd have to establish build pipelines. Can we make it work while keeping it simple? If not, then we probably should reconsider versioneer (although there is probably a way to make it happen with dunamai).

Isn't the `adcircpy` wheel cross-platform when built? I think forcing the user to build it themselves may be the not-simple option, but regardless I've currently implemented in the pull request the logic to pull the latest version from the PyPI API. If we want to support the user installing from source from an earlier version, we could:

1. [track the version in a text file like how Versioneer worked](https://github.com/JaimeCalzadaNOAA/adcircpy/pull/39#discussion_r563883023).
2. somehow parse the user's `pip install adcircpy==X.X.X` command and use that version number in the install
