### ISSUE TITLE
Building TPXO database fails

### ISSUE THREAD

**Issue by mwandres** [oceanmodeling/adcircpy#8]
I just installed adcircpy (I use Anaconda on Windows 10) and am now trying to look at my fort.14 grid. When trying to import
` from AdcircPy.Model import AdcircMesh `
or
` from AdcircPy import read_mesh `
I get the following error 

> URLError: <urlopen error ftp error: URLError("ftp error: error_perm('550 tpxo9_netcdf.tar.gz: No such file or directory')")>

Note, I have not installed Adcirc (or the TPXO database) as I'm just using the grid in SWAN at the moment. I haven't properly dug into the code yet but from the description of adcircpy I should be able to simply read the mesh. Any idea why I need TPXO for that? Thanks for your help.

**Comment by jreniel** [comment]
In the past the TPXO file was freely available for download and the package would stage it for you. I just merged the dev branch into the master which has more updated code and it doesn't require the TPXO file. Try using this new version. I have not pushed any new updates to this repo in a long time so I'm not sure how much of it is actually working, and the namespace may have changed. Please take a look at the newer examples to see if the namespaces have changed. I apologize for any inconvenience that you may encounter when using this package. This package has not received any support from the ADCIRC community and therefore it has been only myself maintaining it, so although I make sure it works for me for my day-to-day workflows, I am not very motivated to keep the repo up-to-date. I may update to the more recent code that I have on my workstation if you are interested.

**Comment by jreniel** [comment]
Additional note: for reading the mesh on this new version you may do:
`from adcirpy.mesh import AdcircMesh` 
`mesh = AdcircMesh.open(fort14, crs=4326)`

**Comment by mwandres** [comment]
Great, works like a dream after installing the new version. Much appreciated! The package looks quite powerful actually (as far as I can tell after looking at it for about 10 minutes). Awesome work! Definitely interested in an up-to-date repository. Thanks!

**Comment by jreniel** [comment]
I have updated the repo with all the new code I have available. Please see the examples directory for the updated usage examples. Thanks.
