### ISSUE TITLE
`make_plot`

### ISSUE THREAD

**Issue by krober10nd** [oceanmodeling/adcircpy#99]
```
plot_mesh myfort.14 --crs=EPSG:4326
```

Does not appear to produce a plot nor show anything to the screen. I guess this functionality isn't yet implemented?

**Comment by jreniel** [comment]
It was, and should be. I just confirmed it's not showing the plot, but it definitely should be.

**Comment by jreniel** [comment]
I wonder if this problem is showing up on the other CLI plotting routines.

**Comment by krober10nd** [comment]
![working](https://user-images.githubusercontent.com/18619644/120014885-f88fe680-bfb8-11eb-828f-5e11204aa3b1.png)

maxele is working. I don't really do fort.61's so don't have any around to test.

**Comment by krober10nd** [comment]
I'm sure you aware of the ongoing jet colormap debates. Perhaps it'd be nice to have `cmocean` to color the maps?

**Comment by jreniel** [comment]
> maxele is working. I don't really do fort.61's so don't have any around to test.
>

Good to know, thanks for checking!

**Comment by jreniel** [comment]
> I'm sure you aware of the ongoing jet colormap debates. Perhaps it'd be nice to have `cmocean` to color the maps?

I'm actually not aware of any such debates. I'm pretty happy with these colormaps (for the fort.14's). In the case that the mesh only has wet values, it takes the red-white-blue approach, so as to be able to distinguish the "middle" values.  If the mesh contains topobathy values then it builds a custom cmap. The colormaps are dynamically adjusted to  the user's vmin and vmax. 

Anyways, if you want to implement other colormap options we can discuss it. Right now jet right now is the default for maxele, but I think you can pass any cmap on the CLI, and that can potentially inclyde `cmocean` colormaps.


![image](https://user-images.githubusercontent.com/19892302/120017201-9680b280-bfb3-11eb-9a89-b31075beea18.png)

**Comment by krober10nd** [comment]
yea, that's fine. I see the option to add your own custom colormap. 

Anyway, if you have time

https://predictablynoisy.com/posts/2018/2018-06-04-makeitpop/
